### ISSUE TITLE
all_fields_required fails on nil pointer

### ISSUE THREAD

**Issue by pavolloffay** [chrusty/protoc-gen-jsonschema#40]
All fields required ` ~/bin/protoc/bin/protoc --jsonschema_out=all_fields_required:.  config.proto` fails on `nil` pointer for https://github.com/hypertrace/agent-config/blob/main/config.proto

```bash
~/bin/protoc/bin/protoc --version                                                                                                                                                                            1 ↵ ploffay@Pavols-MacBook-Pro
libprotoc 3.14.0
``` 

```bash
 ~/bin/protoc/bin/protoc --jsonschema_out=all_fields_required:.  config.proto                                                                                                                                              ploffay@Pavols-MBP
WARN[0000] protoc-gen-jsonschema will create multiple MESSAGE schemas from one proto file  proto_filename=config.proto schemas=5
INFO[0000] Generating JSON-schema for MESSAGE            jsonschema_filename=AgentConfig.jsonschema msg_name=AgentConfig proto_filename=config.proto
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x134e978]

goroutine 1 [running]:
github.com/iancoleman/orderedmap.(*OrderedMap).Keys(...)
	/Users/ploffay/projects/golang/src/github.com/iancoleman/orderedmap/orderedmap.go:94
github.com/chrusty/protoc-gen-jsonschema/internal/converter.(*Converter).convertField(0xc00021ff48, 0xc000266300, 0xc00024e800, 0xc00022d500, 0xc000266780, 0xc00026ad90, 0x0, 0x0)
	/Users/ploffay/projects/golang/src/github.com/chrusty/protoc-gen-jsonschema/internal/converter/types.go:278 +0x10d8
github.com/chrusty/protoc-gen-jsonschema/internal/converter.(*Converter).recursiveConvertMessageType(0xc00021ff48, 0xc000266300, 0xc00022d500, 0xc000251218, 0x4, 0xc000266780, 0x0, 0x203001, 0x30, 0x203000)
	/Users/ploffay/projects/golang/src/github.com/chrusty/protoc-gen-jsonschema/internal/converter/types.go:471 +0x41d
github.com/chrusty/protoc-gen-jsonschema/internal/converter.(*Converter).convertField(0xc00021ff48, 0xc000266300, 0xc00024e300, 0xc00022d100, 0xc000266780, 0xc000254d20, 0x1, 0x2)
	/Users/ploffay/projects/golang/src/github.com/chrusty/protoc-gen-jsonschema/internal/converter/types.go:226 +0xbe5
github.com/chrusty/protoc-gen-jsonschema/internal/converter.(*Converter).recursiveConvertMessageType(0xc00021ff48, 0xc000266300, 0xc00022d100, 0x0, 0x0, 0xc000266780, 0xc000266700, 0x0, 0x0, 0x0)
	/Users/ploffay/projects/golang/src/github.com/chrusty/protoc-gen-jsonschema/internal/converter/types.go:471 +0x41d
github.com/chrusty/protoc-gen-jsonschema/internal/converter.(*Converter).convertMessageType(0xc00021ff48, 0xc000266300, 0xc00022d100, 0x1, 0x1, 0xc00026a1c0)
	/Users/ploffay/projects/golang/src/github.com/chrusty/protoc-gen-jsonschema/internal/converter/types.go:309 +0xba
github.com/chrusty/protoc-gen-jsonschema/internal/converter.(*Converter).convertFile(0xc00021ff48, 0xc00022d000, 0xc00021fb40, 0x1, 0x1, 0xc00026a000, 0xc00021faf0)
	/Users/ploffay/projects/golang/src/github.com/chrusty/protoc-gen-jsonschema/internal/converter/converter.go:186 +0x759
github.com/chrusty/protoc-gen-jsonschema/internal/converter.(*Converter).convert(0xc00021ff48, 0xc0001d4380, 0xc00021fdf8, 0x1, 0x1)
	/Users/ploffay/projects/golang/src/github.com/chrusty/protoc-gen-jsonschema/internal/converter/converter.go:234 +0x767
github.com/chrusty/protoc-gen-jsonschema/internal/converter.(*Converter).ConvertFrom(0xc00021ff48, 0x146e160, 0xc000010010, 0x1, 0x1, 0x2)
	/Users/ploffay/projects/golang/src/github.com/chrusty/protoc-gen-jsonschema/internal/converter/converter.go:61 +0x285
main.main()
	/Users/ploffay/projects/golang/src/github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema/main.go:34 +0x1b0
--jsonschema_out: protoc-gen-jsonschema: Plugin failed with status code 2.
```

### Steps to reproduce:
1. clone https://github.com/hypertrace/agent-config
2. add `package org.hypertrace;` to the `config.proto`
3. run `~/bin/protoc/bin/protoc --jsonschema_out=all_fields_required:.  config.proto`

**Comment by chrusty** [comment]
Thanks for reporing this, @pavolloffay. Looks like some sloppy assumptions around pointers. I've fixed it now, and tested it against your proto.

See https://github.com/chrusty/protoc-gen-jsonschema/commit/492f7d258b6a84e894d586787e461c8ceaadf6cc for the details if you're interested, but in any case you should be able to install the latest master branch to have your fix.

Thanks for your interest!

**Comment by pavolloffay** [comment]
awesome thanks for the fix @chrusty! 

Keep up doing great work :)
